name: jeepr
channels:
- clinicalgraphics
- conda-forge
- defaults
dependencies:
- vtk=7.1.0=py36_3  # via clinicalgraphics
- appnope=0.1.0=py36_0
- backports=1.0=py36_1
- backports.functools_lru_cache=1.4=py36_1
- blas=1.1=openblas
- bleach=2.0.0=py36_0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- coverage=4.4.1=py36_0
- cycler=0.10.0=py36_0
- decorator=4.1.2=py36_0
- entrypoints=0.2.3=py36_1
- freetype=2.7=1
- h5py=2.7.1=py36_1
- hdf5=1.8.18=1
- html5lib=0.999999999=py36_0
- icu=58.1=1
- ipykernel=4.6.1=py36_0
- ipython=6.2.1=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=7.0.3=py_0
- jedi=0.10.2=py36_0
- jinja2=2.9.6=py36_0
- jpeg=9b=1
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_0
- jupyter_client=5.1.0=py36_0
- jupyter_console=5.2.0=py36_0
- jupyter_core=4.3.0=py36_0
- libgfortran=3.0.0=0
- libpng=1.6.28=1
- libsodium=1.0.10=0
- markupsafe=1.0=py36_0
- matplotlib=2.1.0=py36_0
- mistune=0.7.4=py36_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py36_0
- ncurses=5.9=10
- nose=1.3.7=py36_2
- notebook=5.2.0=py36_1
- numpy=1.13.3=py36_blas_openblas_200
- openblas=0.2.19=2
- openssl=1.0.2l=0
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_0
- prompt_toolkit=1.0.15=py36_0
- ptyprocess=0.5.2=py36_0
- py=1.4.34=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- pytest=3.2.3=py36_0
- pytest-cov=2.5.1=py36_0
- pytest-mpl=0.9=py_0
- python=3.6.3=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pyzmq=16.0.2=py36_2
- qt=5.6.2=h9e3eb04_4
- qtconsole=4.3.1=py36_0
- readline=6.2=0
- scipy=0.19.1=py36_blas_openblas_202
- setuptools=36.6.0=py36_1
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.11.0=py36_1
- sqlite=3.13.0=1
- terminado=0.6=py36_0
- testpath=0.3.1=py36_0
- tk=8.5.19=2
- tornado=4.5.2=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.30.0=py_1
- widgetsnbextension=3.0.6=py36_0
- xz=5.2.3=0
- zeromq=4.2.1=1
- zlib=1.2.8=3
- pip:
  - backports.functools-lru-cache==1.4
  - beautifulsoup4==4.6.0
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.15
  - bruges
